apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart-service
  template:
    metadata:
      labels:
        app: cart-service
    spec:
      imagePullSecrets:
        - name: ocir-secret
      initContainers:
        - name: prisma-migrate
          image: iad.ocir.io/idgxrtixsdtd/ecommerce:cart
          imagePullPolicy: Always
          command: ["/bin/sh", "-c"]
          args:
            - echo "DATABASE_URL=$DATABASE_URL" > .env && npx prisma migrate deploy
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres-service:5432/cart"
      containers:
        - name: cart-service
          image: iad.ocir.io/idgxrtixsdtd/ecommerce:cart
          imagePullPolicy: Always
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 4003
          env:
            - name: PORT
              value: "4003"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres-service:5432/cart"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:password@rabbitmq-service:5672"
            - name: REDIS_URL
              value: "redis://redis-service:6379/0"
            - name: TAX_RATE
              value: "0.18"
            - name: BASE_URL
              value: "http://cart-service:4003"
            - name: CLIENT_URL
              value: "http://api-gateway:4000"
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service
spec:
  selector:
    app: cart-service
  ports:
    - port: 4003
      targetPort: 4003
