apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: email
  template:
    metadata:
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: ecommerce-email:latest
          ports:
            - containerPort: 5000
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "5000"

            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:password@rabbitmq-service:5672"

            - name: SMTP_HOST
              value: "smtp-relay.brevo.com"

            - name: SMTP_SECURE
              value: "false"

            - name: SMTP_PORT
              value: "587"

            - name: SMTP_FROM
              value: "tomarrohit3240@gmail.com"
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: SMTP_USER

            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: email-secrets
                  key: SMTP_PASS
---
apiVersion: v1
kind: Service
metadata:
  name: email-service
spec:
  selector:
    app: email
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
