apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    # Essential for Next.js to handle large payloads or file uploads if needed
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
spec:
  ingressClassName: nginx 
  tls:
  - hosts:
    - rohit-ecommerce-microservice.dedyn.io
    secretName: ecommerce-tls-prod
  rules:
  - host: rohit-ecommerce-microservice.dedyn.io
    http:
      paths:
      # ðŸš¨ RULE 1: Backend API Traffic
      # Any request starting with /api goes to the Backend Gateway
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: api-gateway
            port:
              number: 4000
      
      # ðŸš¨ RULE 2: Frontend Traffic (The Catch-All)
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
