apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      initContainers:
        - name: prisma-migrate
          image: ecommerce-monorepo-orders-service
          imagePullPolicy: IfNotPresent
          command: ["npx", "prisma", "migrate", "deploy"]
          env:
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres-service:5432/orders"
      containers:
        - name: orders
          image: ecommerce-monorepo-orders-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4004
          env:
            - name: PORT
              value: "4004"
            - name: NODE_ENV
              value: "production"
            - name: DATABASE_URL
              value: "postgresql://postgres:password@postgres-service:5432/orders"
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:password@rabbitmq-service:5672"
            - name: REDIS_URL
              value: "redis://redis-service:6379/0"
            # Secrets
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_SECRET_KEY
            - name: STRIPE_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_WEBHOOK_SECRET
            - name: STRIPE_PUBLISHABLE_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secrets
                  key: STRIPE_PUBLISHABLE_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: orders-service
spec:
  selector:
    app: orders
  ports:
    - port: 4004
      targetPort: 4004
