services:
  nginx:
    build: ./docker/nginx
    ports:
      - "${API_GATEWAY_PORT}:80"
    depends_on:
      - api-gateway
      - identity
      - orders
    networks:
      - backend

  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_ROOT_USER}
      POSTGRES_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      IDENTITY_DB_USER: ${IDENTITY_DB_USER}
      IDENTITY_DB_PASS: ${IDENTITY_DB_PASS}
      IDENTITY_DB_NAME: ${IDENTITY_DB_NAME}

      ORDERS_DB_USER: ${ORDERS_DB_USER}
      ORDERS_DB_PASS: ${ORDERS_DB_PASS}
      ORDERS_DB_NAME: ${ORDERS_DB_NAME}

      CATALOG_DB_USER: ${CATALOG_DB_USER}
      CATALOG_DB_PASS: ${CATALOG_DB_PASS}
      CATALOG_DB_NAME: ${CATALOG_DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    networks:
      - backend
    restart: unless-stopped

  # RABBITMQ
  rabbitmq:
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - backend
    restart: unless-stopped

  # REDIS
  redis:
    image: redis:alpine
    container_name: redis-ecommerce
    ports:
      - "6379:6379"
    volumes:
      - redis_ecommerce_data:/data
    command: redis-server --databases 16
    networks:
      - backend
    restart: unless-stopped

  api-gateway:
    build:
      context: .
      dockerfile: apps/api-gateway/Dockerfile
    environment:
      - PORT=3000
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
    depends_on:
      - redis
    networks:
      - backend

  # Identity Microservice
  identity:
    build:
      context: .
      dockerfile: apps/identity/Dockerfile
    environment:
      - PORT=3001
      # Dynamic Connection String
      - DATABASE_URL=postgresql://${IDENTITY_DB_USER}:${IDENTITY_DB_PASS}@postgres:5432/${IDENTITY_DB_NAME}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      - REDIS_HOST=${REDIS_HOST}
      - CLIENT_URL=${CLIENT_URL}
      - BASE_URL=/api/auth
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - backend

  # Orders Microservice
  orders:
    build:
      context: .
      dockerfile: apps/orders/Dockerfile
    environment:
      - PORT=3003
      # Dynamic Connection String
      - DATABASE_URL=postgresql://${ORDERS_DB_USER}:${ORDERS_DB_PASS}@postgres:5432/${ORDERS_DB_NAME}
      - RABBITMQ_URL=amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - postgres
      - redis
      - rabbitmq
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  postgres_data:
  redis_ecommerce_data:
  rabbitmq_data:
